version: '2.3'
services:
  journal:
    image: samihsoylu/journal
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=journal
      - DB_PASSWORD=journal
      - DB_SCHEMA=journal
      - DEBUG_MODE=true
      - USERNAME=demouser
      - PASSWORD=demopass
      - EMAIL_ADDRESS=user@example.com
  mariadb:
    image: mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=journal
      - MARIADB_PASSWORD=journal
      - MARIADB_DATABASE=journal
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: