name: ci

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Code quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/7.4@master
        with:
          args: validate --no-interaction --strict

      - name: Install dependencies
        uses: MilesChou/composer-action/7.4@master
        with:
          args: install --prefer-dist --no-progress

      - name: Check for syntax errors
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/parallel-lint
          args: --exclude vendor/ .

      - name: Validate code style
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/php-cs-fixer
          args: fix -v --dry-run --config=.php-cs-fixer.dist.php --using-cache=no

      - name: Static code analysis
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: php
          args: -d memory_limit=1G ./vendor/bin/phpstan -vvv analyse -c phpstan.neon

      - name: Set config for PHP version compatibility analysis
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/phpcs
          args: --config-set installed_paths vendor/phpcompatibility/php-compatibility
      - name: Analyse PHP version compatibility
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/phpcs
          args: -p private/lib --standard=PHPCompatibility --runtime-set testVersion 7.4-
  test74:
    name: PHP 7.4 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: MilesChou/composer-action/7.4@master
        with:
          args: install --prefer-dist --no-progress

      - name: Unit tests
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/phpunit
          args: tests
  test80:
    name: PHP 8.0 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: MilesChou/composer-action/8.0@master
        with:
          args: install --prefer-dist --no-progress

      - name: Unit tests
        uses: MilesChou/composer-action/8.0@master
        with:
          entrypoint: ./vendor/bin/phpunit
          args: tests
